### PR TITLE
Update to allow mocking

### PR DESCRIPTION
**Pull request by dustinlessard-wf**
<h3>Update to allow mocking</h3>

<p>The following change allows a third party mocking library (like Mockolate) to properly mock 'Observable.value'.
</p>

### CODE REVIEW

**Comment by richardszalay** [comment]
ClosureObservable is very much an implementation class so I'd really rather not.

What's your use case for mocking Observable.value? For most scenarios, I would imagine mocking your model object so that _it_ returns a custom IObservable (Observable.value, Observable.throwError) would be a much better fit to enable test scenarios.

Think of IObservable like a List. You would never mock List, you would simply mock the object that returns a list so that it returns a specific, known, set of values.

Take a look at the raix unit tests and you'll see that there's already a significant amount that can be done within the existing APIs.

**Comment by dustinlessard-wf** [comment]
We've been porting over a bunch of legacy code to return an IObservable.  Within unit tests that exercise this code, we needed a means of allowing our chosen mocking framework to quickly and easily mock the returned object out.  We use Mockolate for this purpose, and our code with this change becomes as simple as :

``` actionscript
stub(classUnderTest).method("doSomething").returns(Observable.value(true));
```

Without this change, Mockolate cannot properly interrogate the ClosureObservable class, and with the amount of unit-tests and code we're dealing with, this is the quickest and best solution for us.  We've forked this repo and made this change within our fork, but thought others might benefit from this as well.

I tend to think of IObservable as a suped-up composeable promise, and it is from that perspective that I seek to mock it out.

**Comment by richardszalay** [comment]
Interesting, I can't remember why Mockolate needs to query the type sent to the returns() method, but having written an AVM mocking framework I can understand why it might be. 

I'd rather not expose internal classes for the purpose of testing but, TBH, a simple workaround would be for you to create a public IObservable implementation that simply delegates it's calls to another instance:

``` ActionScript
// Mockito requires public classes in returns()
public class PublicDelegatingObservable extends AbsObservable
{
    private var _inner : IObservable;

    public function PublicDelegatingObservable(inner : IObservable)
    {
        this._inner = inner;
    }

    public override function subscribeWith(observer : IObserver) : ICancelable
    {
        return inner.subscribeWith(observer);
    }
}

// Global
public function mockValueObservable(inner : IObservable)
{
    return new PublicDelegatingObservable(inner);
}
```

Then you can use it like this:

``` ActionScript
stub(classUnderTest).method("doSomething")
    .returns(mockValueObservable(Observable.value(true)));
```

Since the value being supplied to returns() is now public, it will work as expected.

**Comment by dustinlessard-wf** [comment]
@richardszalay - thank you for the feedback.  I agree with you that exposing that class isn't ideal and agree that your proposed solution could work.  I'm going to get some consensus around which approach is favored most by our developers, though I'm now personally leaning to what you've proposed.

**Pull request closed without merging**
